rhs:
  image:
    repository: 447655722442.dkr.ecr.us-east-1.amazonaws.com/reverse-hash-service
    tag: latest
  service:
    port: 8080

db:
  image:
    repository: postgres
    tag: latest
  env:
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: iden3
    POSTGRES_DB: rhs
  persistence:
    storageClass: gp2
    size: 5Gi

traefik:
  ports:
    web:
      exposedPort: 80
    websecure:
      exposedPort: 443
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # or "alb" based on your setup