apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reverse-hash-service.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "reverse-hash-service.name" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "reverse-hash-service.name" . }}-db
    spec:
      containers:
      - name: db
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        env:
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.db.env.POSTGRES_PASSWORD }}"
        - name: POSTGRES_USER
          value: "{{ .Values.db.env.POSTGRES_USER }}"
        - name: POSTGRES_DB
          value: "{{ .Values.db.env.POSTGRES_DB }}"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: init-sql
        configMap:
          name: postgres-init
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
