apiVersion: v1
kind: Service
metadata:
  name: {{ include "reverse-hash-service.fullname" . }}-rhs
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rhs.service.port }}
      targetPort: {{ .Values.rhs.service.port }}
  selector:
    app: {{ include "reverse-hash-service.name" . }}-rhs
